all:
  vars:
    ansible_user: root
    ansible_password: Test123
    ansible_connection: ssh
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
  children:
    syd1:
      children:
        syd1_leafs:
          hosts:
            syd1-lef-01:
              ansible_host: 172.16.100.11
            syd1-lef-02:
              ansible_host: 172.16.100.12
            syd1-lef-03:
              ansible_host: 172.16.100.13
            syd1-lef-04:
              ansible_host: 172.16.100.14
        syd1_spines:
          hosts:
            syd1-spn-01:
              ansible_host: 172.16.100.15
            syd1-spn-02:
              ansible_host: 172.16.100.16
        syd1_bgws:
          hosts:
            syd1-bgw-01:
              ansible_host: 172.16.100.17
            syd1-bgw-02:
              ansible_host: 172.16.100.18
